### ISSUE TITLE
Update version on npm

### ISSUE THREAD

**Issue by hrueger** [Julusian/pkg-prebuilds#1]
Hi @Julusian,
do you plan to release a new version to npm? I just spent 30 minutes trying to figure out why it would fail in CI with `Built binary does not exist!` until I found that the version on npm does not yet care about the `--baseDir` argument.
Thanks!

Edit: in the meantime, I can use the version from GitHub, I just thought I'd mention it.

**Comment by Julusian** [comment]
this is published now.

I probably shouldnt have pushed that to master before I had done the testing I wanted and was ready to publish it. Sorry about that..
