### ISSUE TITLE
more detailed error

### ISSUE THREAD

**Issue by dvirtz** [Julusian/pkg-prebuilds#3]
Is it possible to add the list of candidates to the reported error when failing to find a prebuilt module?
It will ease the debug when my library users fail to load my library due to this error.
Currently it only says
```
Failed to find binding for <module_name>
```

**Comment by senner007** [comment]
I have a somewhat similar issue. When I bundle a node.js app with webpack the bundled file fails to run due to the above error
Without bundling it runs fine.

Any ideas?

**Comment by Julusian** [comment]
in 1.0.0 the error now lists the paths it checked
